file_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from portal.views import AdminLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', AdminLoginView.as_view(template_name='portal/login-admin.html'), name='admin_login'),
    path('', include('portal.urls', namespace='portal')),
]

portal/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from .views import DashboardView, file_upload, UploadedFileView

app_name = 'portal'

urlpatterns = [
	path('home/', DashboardView.as_view(), name='home'),
    path('file-upload/', file_upload, name='file-upload'),
    path('file-list/', UploadedFileView.as_view(), name='file-list'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/models.py
from django.db import models
from django.template.defaultfilters import slugify

from django.contrib.auth.models import AbstractUser
from django.dispatch.dispatcher import receiver
from django.contrib.auth.models import User

from django.core.validators import FileExtensionValidator
from django.contrib.contenttypes.fields import GenericRelation
from django_cleanup.signals import cleanup_post_delete
from sorl.thumbnail import delete

from django.db.models import Func

class User(AbstractUser):
    pass

class File(models.Model):
    file = models.FileField(
        upload_to='files/', 
        default=None, 
        blank = False,
    )
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE)

    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'File'
        verbose_name_plural = 'Files'

portal/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django.utils.translation import gettext_lazy as _

from .models import File

class AdminAuthForm(AuthenticationForm):
    
    error_messages = {
        'invalid_login': _("Incorrect username or password"),
        'invalid': _("Invalid user input!"),
        'inactive': _("This account is inactive."),
    }

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(self.request, username=username, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                if self.user_cache:
                    self.confirm_login_allowed(self.user_cache)
                else:
                    raise forms.ValidationError(
                        self.error_messages['invalid'],
                        code='invalid',
                    )

        return self.cleaned_data


class FileUploadForm(forms.ModelForm):
    
    class Meta:
        model = File
        fields = [
            'file',
        ]

portal/views.py
import datetime
from django.contrib import messages
from django.shortcuts import redirect

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.views import LoginView
from django.views.generic import ListView
from django.db.models import Q
from django.conf import settings
from django.http import HttpResponseRedirect
from django.utils.http import is_safe_url
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, render_to_response

from .forms import AdminAuthForm, FileUploadForm
from .models import File

from rest_framework.views import APIView


class AppDeleteAPIView(APIView):
    
    def post(self, request):
        entry_id = request.POST.get('app_name') # Here app_name in the AJAX hold the entry_id

        app = get_object_or_404(App, pk=entry_id)

        count = File.objects.filter(app__app_name = app).count() - 1 # By clicking delete button one count is already decreased
        
        if (count < 1): # When an app has no other instance lef but itself, excute the following
            File.objects.filter(id=entry_id).delete()
            AppAuthor.objects.filter(app_name = app).delete()  

        else: # If an app has other versions left
            File.objects.filter(id=entry_id).delete()
            # When a version of an App is deleted, the last inactive version will be activated 
            version = File.objects.filter(app__app_name=app)    
            last_version = 0
            for v in version:
                if last_version < v.app_version_code:
                    last_version = v.app_version_code
                v.save()
            App.objects.filter(app__app_name=app, app_version_code = last_version).update(is_active = True)

        return Response({
            'status': status.HTTP_202_ACCEPTED,
            'message': 'File deleted.'
        })

class AdminLoginView(LoginView):
    form_class = AdminAuthForm

    def get_success_url(self):
        if self.request.user:
            return reverse('portal:home')
        else:
            return reverse('portal:home')

    def form_invalid(self, form):
        # error message
        error_messages = []
        message = form.errors.get_json_data()
        for _, message_value in message.items():
            error = message_value[0]['message']
            error_messages.append(error)
        message_ = ' And '.join(error_messages)

        # Check user_type
        user_type = 'asdfa'
        if user_type:
            messages.error(self.request, message_)
            return redirect('admin_login')
        elif user_type:
            messages.error(self.request, message_)
            return redirect('admin_login')
        return self.render_to_response(self.get_context_data(form=form))

    def get_redirect_url(self):
        """Return the user-originating redirect URL if it's safe."""
        redirect_to = self.request.POST.get(
            self.redirect_field_name,
            self.request.GET.get(self.redirect_field_name, '')
        )
        url_is_safe = is_safe_url(
            url=redirect_to,
            allowed_hosts=self.get_success_url_allowed_hosts(),
            require_https=self.request.is_secure(),
        )
        return redirect_to if url_is_safe else ''

class DashboardView(ListView):
    template_name = 'portal/home.html'
    context_object_name = 'files'
    ordering = ['date']

    def get_queryset(self):

        queryset = {
        }
        return queryset

def file_upload(request):
    if request.method == 'POST':
        aul_form = FileUploadForm(request.POST, request.FILES, instance=request.user)
        try:
            author = request.user.username
            author_name = User.objects.get(user__username=author)

            if aul_form.is_valid():
                app_file = aul_form.cleaned_data['app_file']
                app_logo = aul_form.cleaned_data['app_logo']
                app_name = aul_form.cleaned_data['app_name']  
                app_version_name = aul_form.cleaned_data['app_version_name']
                app_short_description = aul_form.cleaned_data['app_short_description']
                app_long_description = aul_form.cleaned_data['app_long_description']
                app_release_note = aul_form.cleaned_data['app_release_note']
                app_update_notice = aul_form.cleaned_data['app_update_notice']

                if app_file.name.endswith('.apk'):
                    app_file.name =  unquote(app_name).replace(' ', '_') + '_' + 'version' + '_' + app_version_name + '.apk'
                    
                else:
                    messages.error(request, 'Please upload APK file', extra_tags = 'apk_ext')
                    return render(request, 'portal/file_upload.html', { 'aul_form': aul_form })

                if not app_logo or app_logo==None:
                    messages.error(request, 'Insert a logo in jpg or png', extra_tags = 'logo_empty')
                    return render(request, 'portal/file_upload.html', { 'aul_form': aul_form })

                elif not app_logo.name.endswith(('jpg', 'png', 'jpeg', 'JPG', 'JPEG', 'PNG')):
                    messages.error(request, 'Only jpg or png is supported format for logo', extra_tags = 'logo_ext')
                    return render(request, 'portal/file_upload.html', { 'aul_form': aul_form })

                if App.objects.filter(app__app_name = app_name).exists():
                    messages.error(request, 'same app name already exist', extra_tags = 'app_name_exist')
                    return render(request, 'portal/file_upload.html', { 'aul_form': aul_form })
                
                fs = FileSystemStorage()
            
                file = fs.save( 'apk/' + unquote(app_file.name).replace(' ', '_'), app_file)
        
                # the fileurl variable now contains the url to the file. This can be used to serve the file when needed. 
                fileurl = unquote(fs.url(file)).replace(' ', '_')

                apk = APK(settings.BASE_DIR+fileurl)

                app_version_code = int(apk.version_code)

                app_package_name = apk.package
                if App.objects.filter(app_package_name = app_package_name).exists():
                    messages.error(request, 'App name with the same package name already exist', extra_tags = 'package_name_exist')
                    return render(request, 'portal/file_upload.html', { 'aul_form': aul_form })

                AppAuthor.objects.create(author=author_name, app_name=app_name)
                app = AppAuthor.objects.get(app_name=app_name)

                App.objects.create(
                    app_file=fileurl.replace('/media',''),
                    app_logo=app_logo,
                    app=app, 
                    app_version_code=app_version_code, 
                    app_version_name=app_version_name, 
                    app_package_name=app_package_name, 
                    app_short_description=app_short_description, 
                    app_long_description=app_long_description,
                    app_release_note=app_release_note,
                    app_update_notice=app_update_notice,    
                )
                
                return redirect('portal:app-developer-app-list')
        
            else:
                messages.error( request, 'Invalid Input', extra_tags = 'form_invalid' )
                return render(request, 'portal/file_upload.html', { 'aul_form': aul_form })

        except:
            messages.error( request, 'Form Crashed', extra_tags = 'form_crashed' )
            return render(request, 'portal/file_upload.html', { 'aul_form': aul_form })
    else:
        aul_form = FileUploadForm(instance=request.user)
        return render(request, 'portal/file_upload.html', { 'aul_form': aul_form })

class UploadedFileView(ListView):
    model = File
    template_name = 'portal/file_list.html'
    context_object_name = 'files'
    paginate_by = 10

    def get_queryset(self):
        author = self.request.user.username
        author_name = AppDeveloper.objects.get(user__username=author)
        form = self.request.GET.get('q')
        if form:
            return App.objects.filter(
                Q(app__app_name__icontains=form) | 
                Q(app_version_code__icontains=form) |
                Q(app_version_name__icontains=form) |
                Q(app_package_name__icontains=form) | 
                Q(app_short_description__icontains=form)
            ).order_by('pub_date').reverse()
        queryset = App.objects.filter(app__author=author_name).order_by('pub_date').reverse()
        return queryset

    def get_context_data(self, **kwargs):
        kwargs['q'] = self.request.GET.get('q')
        return super().get_context_data(**kwargs)

portal/templates/portal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>File Dashboard</title>
    <!-- Custom fonts for this template-->
    <link href="{% static 'portal/assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css"
        href="https://cdn.materialdesignicons.com/5.3.45/css/materialdesignicons.min.css">
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static 'portal/assets/css/sb-admin-2.css' %}" rel="stylesheet">
</head>
<div class="loader"></div>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center " href="">
                <div class="sidebar-brand-text mx-3">File Platform</div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'portal:home' %}">
                    <i class="mdi mdi-view-dashboard" aria-hidden="true"></i>
                    <span>Dashboard</span></a>
            </li>
            <!-- Heading -->
            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                    data-parent="#accordionSidebar">
                    <div class="pt-0 pb-0 collapse-inner rounded">
                        <a class="collapse-item" href="{% url 'portal:file-upload' %}">File Upload</a>
                    </div>
                    <div class="pt-0 pb-0 collapse-inner rounded">
                        <a class="collapse-item" href="{% url 'portal:file-list' %}">File List</a>
                    </div>

                </div>
            </li>
            <!-- Nav Item - Tables -->
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-transparent topbar static-top">
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>
                <!-- Topbar Search -->
                <!-- Topbar Navbar -->
                <ul class="navbar-nav">
                    <li>
                        <h4 class="mt-3">File Manager Portal</h4>
                    </li>
                </ul>
                           
            {% block content %}{% endblock %}
            <footer class="footer">
                <div class="container">
                </div>
            </footer>
            <!--End footer-->
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    
            </div>
        </div>
    </div>
</body>

</html>
<!-- Bootstrap core JavaScript-->
<script src="{% static 'portal/assets/vendor/jquery/jquery.min.js' %}"></script>
<!-- Core plugin JavaScript-->
<script src="{% static 'portal/assets/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<!-- Custom scripts for all pages-->
<script src="{% static 'portal/assets/js/sb-admin-2.js' %}"></script>
<script src="{% static 'portal/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
{% block script%}
<!-- Page level plugins -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css" rel="stylesheet" type="text/css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
{% endblock %}

portal/templates/portal/file_list.html
{% extends "portal/app_developer_base.html" %}
{% block content %}
<!-- Begin Page Content -->
{% if success_message %}
    <div class="alert alert-success">
        {{ success_message }}
    </div>
{% endif %}
<div class="container-fluid dashboard_item">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
    </div>
    <!-- Content Row -->
    <div class="row">
        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-12 col-md-12 mb-12 mb-3">
            <div class="card h-100 py-2 dashboard_header">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary">
                                <h1 class="h3 mb-0 text-gray-800">App List</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Content Row -->
    <div class="row">
        <div class="col-xl-12">
            <div class="card col-xl-12 col-md-12 col-sm-12 shadow mb-4 dashboard_item_shadow br-10">
                <!-- Card Body -->
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover teble-responsive agency_list_table">
                            <thead>
                                <tr>
                                    <th scope="col">App Entry ID</th>
                                    <th scope="col">App Name</th>
                                    <th scope="col">No. Downloads</th>
                                    <th scope="col">Author</th>
                                    <th scope="col">Description</th>
                                    <th scope="col">Version Code</th>
                                    <th scope="col">Version Name</th>
                                    <th scope="col">Package Name</th>
                                    <th scope="col">Published Date</th>
                                    <th scope="col">Download</th>
                                    <th scope="col">Make <br> Active/Inactive</th>
                                    <th scope="col">Delete</th>
                                </tr>

                            </thead>
                            <tbody>
                                {% for obj in apps %}
                                <tr>
                                    <td class="app_name">{{ obj.id }}</td>
                                    <td class="fixed_td_width"><a
                                            href="{% url 'portal:app-developer-app-details' obj.id %}">{{ obj.app.app_name }}</a>
                                    </td>
                                    <td class="count_number">{{ obj.downloads }}</td>
                                    <td>{{ obj.app.author.user.username }}</td>
                                    <td class="fixed_td_width">{{ obj.app_short_description }}</td>
                                    <td>{{ obj.app_version_code }}</td>
                                    <td class="fixed_td_width">{{ obj.app_version_name }}</td>
                                    <td class="fixed_td_width">{{ obj.app_package_name }}</td>
                                    <td>{{ obj.pub_date | date:"d M Y" }}</td>
                                    <td><a href="{{ obj.app_file.url }}" download
                                            class="btn btn-primary float-center counter download_btn">
                                            <i class="fa fa-download"></i>
                                        </a>
                                    </td>

                                    {% if obj.is_active %}
                                    <td>
                                        <button class="btn btn-dark active_status inactive_btn"
                                            value="False">Deactivate</button>
                                    </td>
                                    {% else%}
                                    <td>
                                        <button class="btn btn-dark active_status active_btn"
                                            value="True">Activate</button>
                                    </td>
                                    {% endif %}

                                    <td>
                                        <button class="btn btn-danger remove_data" data-toggle="modal"
                                            data-target="#removeDataModal">
                                            <i class="fa fa-times"></i>
                                        </button>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {% if is_paginated %}
                        {% if page_obj.has_previous %}
                            <a class="btn btn-outline-info mb-4" href="?page=1 {% if q %} &q={{ q }} {% endif %}">First</a>
                            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}{% if q %} &q={{ q }} {% endif %}">Previous</a>
                        {% endif %}

                        {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                                <a class="btn btn-info mb-4" href="?page={{ num }}{% if q %} &q={{ q }} {% endif %}">{{ num }}</a>
                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                <a class="btn btn-outline-info mb-4" href="?&page={{ num }}{% if q %} &q={{ q }} {% endif %}">{{ num }}</a>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}{% if q %} &q={{ q }} {% endif %}">Next</a>
                            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}{% if q %} &q={{ q }} {% endif %}">Last</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- delete table row modal  -->
<!-- Logout Modal-->
<div class="modal fade" id="removeDataModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to <b class="text-danger">delete
                        this data</b>?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>By selecting "Yes" Your data will be removed permanently. <br> You can go back to
                    previous state by clicking "No"</p>

            </div>
            <div class="modal-footer">
                <form class="tagForm" method="DELETE" action="">
                    {% csrf_token %}
                    <button class="btn btn-primary" onclick="reload()" type="button" data-dismiss="modal">No</button>
                    <a class="btn btn-danger delete_data_permanently" href="#">Yes</a>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- delete table row modal  -->
<!-- End container-fluid-->
{% endblock %}
{% block script %}
<script type="text/javascript">
    function reload(){
        location.reload()
    }
    // remove data
    var app_name;
    var domain = document.location.origin;
    // using jQuery
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    $(".remove_data").click(function () {

        app_name = $(this).closest('td').siblings('td.app_name').text();
        console.log(app_name);
        // get table data
        var that = $(this).closest("tr");
        console.log(that)
        // on click remove data
        $(".delete_data_permanently").click(function () {
            // yes click remove data
            console.log(app_name);
            var url = domain + "/app-delete-api/delete/";
            console.log(url);
            $.ajax({
                url: url,
                dataType: 'json',
                type: 'POST',
                contentType: 'application/x-www-form-urlencoded',
                headers: {
                    "X-CSRFToken": csrftoken
                },
                data: {
                    app_name: app_name,
                    csrfmiddlewaretoken: csrftoken,
                },
                beforeSend: function () { },
                success: function (data) {
                    // console.log(data);
                    that.remove();
                    $('#removeDataModal').modal('hide');
                    reload()
                },
                error: function (jqXhr, textStatus, errorThrown) {

                }
            });
        })
    });

    $(".active_status").click(function () {
        console.log("clicked");
        var that = $(this);
        app_name = $(this).closest('td').siblings('td.app_name').text();
        console.log(app_name);
        var url = domain + "/app-update-api/" + app_name + "/update/";
        console.log(url);
        var activeStatus = $(this).val();
        console.log(activeStatus);
        if (activeStatus == "False") {
            $.ajax({
                url: url,
                dataType: 'json',
                type: 'PUT',
                contentType: 'application/x-www-form-urlencoded',
                headers: {
                    "X-CSRFToken": csrftoken
                },
                data: {
                    is_active: "False",
                    csrfmiddlewaretoken: csrftoken,
                },
                beforeSend: function () { },
                success: function (data) {
                    // console.log(data);
                    that.addClass("active_btn");
                    that.removeClass("inactive_btn");
                    that.text("Activate");
                    that.val("True")
                },
                error: function (jqXhr, textStatus, errorThrown) {

                }
            });
        } else if (activeStatus == "True") {
            $.ajax({
                url: url,
                dataType: 'json',
                type: 'PUT',
                contentType: 'application/x-www-form-urlencoded',
                headers: {
                    "X-CSRFToken": csrftoken
                },
                data: {
                    is_active: "True",
                    csrfmiddlewaretoken: csrftoken,
                },
                beforeSend: function () { },
                success: function (data) {
                    // console.log(data);
                    that.addClass("inactive_btn");
                    that.removeClass("active_btn");
                    that.text("Deactivate");
                    that.val("False")
                },
                error: function (jqXhr, textStatus, errorThrown) {

                }
            });
        }
    });

    $(".counter").click(function () {
        var count_div = $(this).closest('tr').find('.count_number');
        var count_number = parseInt($(this).closest('tr').find('.count_number').text());
        var id = $(this).closest('td').siblings('td.app_name').text();
        
        $.ajax({
            type: "GET",
            url: domain + "/downloadcount/" + id + "/",
            datatype: "html",
            data: $("downloads").serialize(),
            success: function (data) {
                var count_updated_number = count_number + 1;
                $(count_div).text(count_updated_number)
            }
        });
    });

</script>
{% endblock %}